package database

const (
	BlackName                       = "black"
	ConversationName                = "conversation"
	FriendName                      = "friend"
	FriendVersionName               = "friend_version"
	FriendRequestName               = "friend_request"
	GroupName                       = "group"
	GroupMemberName                 = "group_member"
	GroupMemberVersionName          = "group_member_version"
	GroupJoinVersionName            = "group_join_version"
	ConversationVersionName         = "conversation_version"
	GroupRequestName                = "group_request"
	LogName                         = "log"
	ObjectName                      = "s3"
	UserName                        = "user"
	SeqConversationName             = "seq"
	SeqUserName                     = "seq_user"
	StreamMsgName                   = "stream_msg"
	CacheName                       = "cache"
	UserIPLogName                   = "user_ip_log"
	ReceptionistInviteCodeName      = "receptionist_invite_codes"
	CustomerReceptionistBindingName = "customer_receptionist_binding"
	ReceptionistGreetingName        = "receptionist_greeting"
	GreetingSendLogName             = "greeting_send_logs"
)
